---
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  labels:
    app.kubernetes.io/part-of: rollback-sample
    apps.tanzu.vmware.com/workload-type: server
  name: rollback-sample
spec:
  build:
    env:
    - name: BP_WEB_SERVER
      value: nginx
    - name: BP_WEB_SERVER_ROOT
      value: htdocs
  source:
    git:
      ref:
        branch: main
      url: https://github.com/cdelashmutt-pivotal/rollback-webserver-app